name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BACKEND_ECR_REPOSITORY: "backend"
  FRONTEND_ECR_REPOSITORY: "frontend"
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    name: Backend Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::905343638195:role/github-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # O contexto foi alterado para "." (raiz) para que o Dockerfile encontre a pasta /backend
          docker build -f ./dvn-workshop-apps/backend/YoutubeLiveApp/Dockerfile \
            -t $REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG \
            .
          docker push $REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: 'Borghi97/gitops'
          token: ${{ secrets.PAT }}
          path: gitops-repo

      - name: Kustomize Edit Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd gitops-repo
          kustomize edit set image $REGISTRY/$BACKEND_ECR_REPOSITORY=$REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[BOT] Changed backend image to $IMAGE_TAG"
          git push

  frontend:
    name: Frontend Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::905343638195:role/github-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f ./dvn-workshop-apps/frontend/youtube-live-app/Dockerfile \
            -t $REGISTRY/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG \
            .
          docker push $REGISTRY/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: 'Borghi97/gitops'
          token: ${{ secrets.PAT }}
          path: gitops-repo-frontend

      - name: Kustomize Edit Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd gitops-repo-frontend
          kustomize edit set image $REGISTRY/$FRONTEND_ECR_REPOSITORY=$REGISTRY/$FRONTEND_ECR_REPOSITORY:$IMAGE_TAG
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[BOT] Changed frontend image to $IMAGE_TAG"
          git push